name: simple_cookies
description: Easy Cookie-Handling Package for Flutter Web
version: 0.1.0
homepage: https://github.com/jannikhst/cookies.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html:
    git: https://github.com/jannikhst/universal_html.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: